name: Deploy Application

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    #environment: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Log in to Azure using OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_AD_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Show account info (for debugging)
        run: az account show

      - name: ACR Login
        run: az acr login -n magent0

      - name: Build image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          build-args: |
            ARG_LOG_STDOUT=/dev/stdout
            ARG_LOG_STDERR=/dev/stderr
          context: .
          file: Dockerfile
          push: true
          tags: "magent0.azurecr.io/magento246-test:${{ github.sha }}"

      - name: 'Deploy to Azure Web App for Container'
        uses: azure/webapps-deploy@v2
        with:
          app-name: testmagenro
          images: "magent0.azurecr.io/magento246-test:${{ github.sha }}"
